name: Build Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          cd client/
          docker build -t client .
          docker tag client elsiedev/hack254:client
          docker push elsiedev/hack254:client
          cd ..
          cd server/
          docker build -t server .
          docker tag server elsiedev/hack254:server
          docker push elsiedev/hack254:server
 
#       - name: Deploy to EC2 instance
#         uses: easingthemes/ssh-deploy@main
#         with: 
#           host: ${{ secrets.EC2_HOST }}     # EC2 instance IP or DNS
#           username: ${{ secrets.EC2_USER }} # EC2 instance SSH username
#           password: ${{ secrets.EC2_PASS }} # EC2 instance SSH password (or use private key)
#           script: |
#             sudo docker pull elsiedev/hack254:client
#             sudo docker pull elsiedev/hack254:server
#             sudo docker-compose up -d
          
          
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          script: |
            sudo docker pull elsiedev/hack254:client
            sudo docker pull elsiedev/hack254:server
            sudo docker-compose up -d
   
